#REQUIRED
org_name: Vino & Cigarro
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Vino & Cigarro Website
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate.

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: your-email@somedomain.com
org_street_address: 1355 Market Street #Please include suite number on the line below
org_address_suite: Suite 900
org_city: San Francisco
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  94103
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (123) 456-7890

#SOCIAL MEDIA
org_twitter_username:
org_facebook_username:
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: true

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed
